spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/journal
    username: zerowest
    password: pass

  data:
    rest:
      base-path: /api

#  security:
#    user:
#      name: springboot
#      password: isawesome
